# Generated by Django 3.2 on 2021-05-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('id_karyawan', models.CharField(max_length=100)),
                ('posisi', models.CharField(max_length=100)),
            ],
        ),
    ]
